version: '2'
services:
  app:
    build: .
    restart: always
    volumes:
      - ./www/.env:/var/www/html/.env
    volumes_from:
      - volumes_data
    links:
      - database
      - redis
      
  nginx:
    image: nginx:alpine
    ports:
      - 80:80
    links:
      - app
    volumes_from:
      - app
    volumes:
      - ./nginx/app.conf:/etc/nginx/conf.d/default.conf

  redis:
    image: redis:alpine
    ports:
      - 6379:6379

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      - PMA_HOST=database
      - PHP_UPLOAD_MAX_FILESIZE=100M
    ports:
      - 33060:80
    volumes_from:
      - volumes_data
    links:
      - database

  database:
    container_name: database
    image: mariadb:latest
    volumes_from:
      - volumes_data
    environment:
      MYSQL_ROOT_PASSWORD: "secret"
      MYSQL_DATABASE: "homestead"
      MYSQL_USER: "homestead"
      MYSQL_PASSWORD: "secret"

  volumes_data:
    image: tianon/true
    volumes:
      - ./storage/sessions:/sessions
      - ./storage/database:/var/lib/mysql
      - ./storage/log/laravel:/var/log/laravel
      